add conda to github actions bash

diff --git a/.github/workflows/generate-gifs.yml b/.github/workflows/generate-gifs.yml
--- a/.github/workflows/generate-gifs.yml
+++ b/.github/workflows/generate-gifs.yml
@@ -15,8 +15,21 @@ jobs:
 
     - name: Setup environment
       run: |
+        # Install Miniconda if not available
+        if ! command -v conda &> /dev/null
+        then
+            echo "Conda not found, installing..."
+            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
+            bash miniconda.sh -b -p $HOME/miniconda
+            export PATH="$HOME/miniconda/bin:$PATH"
+            conda config --set always_yes yes --set changeps1 no
+            conda update -q conda
+        fi
+    
+        conda init bash
+    
         conda env create -f config/constellationbot_env.yml
-        conda activate constellationbot
+        source activate constellationbot
 
     - name: Generate GIFs
       run: |
